### ISSUE TITLE
Cannot share video to Instagram

### ISSUE THREAD

**Issue by miketalbott** [natsuite/NatShare#109]
When sharing a video file with Natshare 1.2.4 and the user selects instagram, the user receives the error "Something went wrong". I have reproduced this with a blank project and only the Natshare examples. I have tested with NatCorder video and with other generic 720p video files.  (Unity 2019.4.17f1)

This is a regression from earlier versions where sharing video to instagram worked.

**Comment by olokobayusuf** [comment]
This isn't a NatShare error, see:
- https://stackoverflow.com/questions/65197519/instagram-share-extension-returning-error-message-when-sharing-image-via-local-u
- https://stackoverflow.com/questions/65003868/instagram-sharing-to-feed-ios-not-working-uidocumentinteractioncontroller
- https://developer.apple.com/forums/thread/659326
