### ISSUE TITLE
App crash after discarding/canceling a share

### ISSUE THREAD

**Issue by miketalbott** [natsuite/NatShare#110]
To reproduce, enter the share form for a particular app (Facebook, Instagram, iMessages, etc.) and then cancel out of the share and dismiss the iOS share sheet. The app will then crash. This will occur in a blank project with only NatShare 1.2.4 examples. (Unity 2019.4.17f1)

**Comment by olokobayusuf** [comment]
Thanks for reporting this. I'll check it out this weekend.

**Comment by olokobayusuf** [comment]
@miketalbott was just able to reproduce. I'm looking into a fix now.

**Comment by olokobayusuf** [comment]
29b02b9bb0cff580aafa86cc56fb98d12e6ad98d
