### ISSUE TITLE
Xcode linker issue with the bridge code

### ISSUE THREAD

**Issue by subhamC** [natsuite/NatShare#117]
Steps to repro

1.Include the natshare plugin
2.OnbuttonClick put share text code from the document
3. build for xcode
4. press product>build in Xcode 
![IMG-20210414-WA0001](https://user-images.githubusercontent.com/42401998/114669273-51fcc880-9d1f-11eb-99e5-c7cadd6b15ca.jpg)

**Comment by olokobayusuf** [comment]
You are trying to compile for armv7 (32-bit) which is no longer supported. In build settings, set your iOS Deployment Target to iOS 11+.
