### ISSUE TITLE
Cannot save media directly in Camera Roll, it creates an album and puts media into that

### ISSUE THREAD

**Issue by arif69eee** [natsuite/NatShare#120]
Hi Yusuf,

Hope you are doing great! And thanks for your great work "NatCorder - Video Recording API", we purchased it!

On Android I am trying to save images and videos directly into Camera Roll, not under any album. So I wrote code as follows -

var payload = new SavePayload();

I did not set any album here, but it still creates album "Movies" and "Pictures" and puts the medias into those albums. How can I put media directly into Camera Roll, not under any album?

Thank you so much in advance!!

**Comment by olokobayusuf** [comment]
Hey @arif69eee , what device and OS version are you running on? If you're on Android, then this is the default behaviour from Android: https://github.com/natsuite/NatShare/blob/1.2.5/Android/NatShare/src/main/java/api/natsuite/natshare/SavePayload.java#L66-L75

**Comment by arif69eee** [comment]
Hi Yusuf,

Thanks for quick response!

I cannot not see the issue in my Android but the issue was seen in my client's phone, I don't know which version and model he is using.

But I could just solved it. The issue was, when I was setting no album, the NatShare was saving the medias outside of the DCIM folder of Android. So some android devices were not showing the medias in the gallery directly but under an album "Movies" or "Pictures". Now I just put an album name, so it creates that album under the DCIM folder and the gallery app is showing the media directly in the gallery as well as under the newly created album. 

Thanks!

**Comment by olokobayusuf** [comment]
Hm that sounds good. I'm closing this issue.

**Comment by arif69eee** [comment]
Yes please. Thanks!
