### ISSUE TITLE
android Chooser SharePayload Commit Task blocks indefinitely when user closes without selection

### ISSUE THREAD

**Issue by teleportal-andrew** [natsuite/NatShare#122]
On Android
When the Chooser is launched from SharePayload.Commit()
if the user closes the activity without making a selection
an await on SharePlayload.Commit() will block indefinitely

presumably https://github.com/natsuite/NatShare/blob/36ab10097f6dbf7968cd517b5b1aee9b24cd4df1/Android/NatShare/src/main/java/api/natsuite/natshare/SharePayload.java#L108 callback is never getting called because no choice is made

it would be convenient if SharePayload.Commit() also detected if the chooser activity was closed without a choice, and returned with no selection in this case

observed in Android 11

**Comment by olokobayusuf** [comment]
> it would be convenient if SharePayload.Commit() also detected if the chooser activity was closed without a choice, and returned with no selection in this case

This is bad design from the Android folks. Android will not tell you when the activity is closed without a choice. See [this](https://stackoverflow.com/questions/34163473/how-to-get-notified-when-a-user-cancelled-a-sharing-activity) and [this](https://stackoverflow.com/questions/8793825/successful-share-intent-for-android).
