### ISSUE TITLE
Unity asset files is missing?

### ISSUE THREAD

**Issue by jonryborbevobling** [natsuite/NatShare#123]
Hi, I saw that the plugin was updated today. I can only see 1 file in the unity assetstore. Is it intended?

![image](https://user-images.githubusercontent.com/35293007/135242300-af99f1dd-a096-44e2-bc83-39d586276d10.png)

**Comment by olokobayusuf** [comment]
This is correct. NatShare is now distributed from the [NPM package registry](https://www.npmjs.com/package/api.natsuite.natshare), so the Asset Store package simply adds the package to your project's `manifest.json`.
